services:
  app:
    build: .
    # restart: unless-stopped
    ports:
      - "${SERVICE_HOST}:${SERVICE_PORT}"
    env_file:
      .env
    environment:
      - NODE_ENV=${NODE_ENV}
    depends_on:
      postgres: 
        condition: service_healthy
    volumes:
      - .:/app
#      - /app/node_modules

  postgres:
    image: postgres:latest
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    env_file:
      .env
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: "exit 0"
volumes:
  postgres_data: