#version: '3.8'

services:
  app:
    build: .
    restart: always
    ports:
      - "${SERVICE_HOST}:${SERVICE_PORT}"
    env_file:
      - .env
    depends_on:
      - postgres
#    environment:
#      DATABASE_URL: postgres://yourusername:yourpassword@postgres:5432/autostrade_monitoring
    volumes:
      - .:/app
#      - /app/node_modules

  postgres:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    env_file:
      - .env
    ports:
      - "${POSTGRES_HOST}:${POSTGRES_PORT}"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
